name = "MatrixMarket"
uuid = "f617c4c8-c2da-11e8-01e6-abadcf6019ba"
authors = ["Tristan Konolige <tristan.konolige@gmail.com>"]
version = "0.1.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"


[extras]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GZip"]
