name = "MatrixMarket"
uuid = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
authors = ["Tristan Konolige <tristan.konolige@gmail.com>"]
version = "0.4.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
julia = "1"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Downloads", "GZip", "SHA", "Test"]
