name = "MatrixMarket"
uuid = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
authors = ["Tristan Konolige <tristan.konolige@gmail.com>"]
version = "0.3.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GZip"]
